FROM nvcr.io/nvidia/tensorflow:19.04-py3

USER lipreri:stud

# Install system packages
RUN apt-get update

COPY . /app

WORKDIR /app

RUN pip install --upgrade pip
RUN pip install -r requirements.txt


CMD ["python", "train.py"]